-- Kept to SQL that both PostgreSQL and H2 (PostgreSQL mode) accept, so local dev runs the same migrations.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(30)  NOT NULL UNIQUE,
    email         VARCHAR(254) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    display_name  VARCHAR(60)  NOT NULL,
    bio           VARCHAR(500),
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE stories (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR(120) NOT NULL,
    description      VARCHAR(600) NOT NULL,
    author_id        BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    published        BOOLEAN      NOT NULL DEFAULT FALSE,
    open_to_branches BOOLEAN      NOT NULL DEFAULT TRUE,
    views            INTEGER      NOT NULL DEFAULT 0,
    like_count       INTEGER      NOT NULL DEFAULT 0,
    chapter_count    INTEGER      NOT NULL DEFAULT 0,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_stories_author ON stories (author_id);
CREATE INDEX idx_stories_published_created ON stories (published, created_at);

CREATE TABLE story_tags (
    story_id BIGINT      NOT NULL REFERENCES stories (id) ON DELETE CASCADE,
    tag      VARCHAR(30) NOT NULL,
    PRIMARY KEY (story_id, tag)
);
CREATE INDEX idx_story_tags_tag ON story_tags (tag);

CREATE TABLE chapters (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_id     BIGINT        NOT NULL REFERENCES stories (id) ON DELETE CASCADE,
    parent_id    BIGINT        REFERENCES chapters (id) ON DELETE CASCADE,
    author_id    BIGINT        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    title        VARCHAR(120)  NOT NULL,
    choice_label VARCHAR(140),
    content      VARCHAR(60000) NOT NULL,
    depth        INTEGER       NOT NULL DEFAULT 0,
    views        INTEGER       NOT NULL DEFAULT 0,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_chapters_story ON chapters (story_id);
CREATE INDEX idx_chapters_parent ON chapters (parent_id);
CREATE INDEX idx_chapters_author ON chapters (author_id);

CREATE TABLE comments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_id   BIGINT        NOT NULL REFERENCES stories (id) ON DELETE CASCADE,
    author_id  BIGINT        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    content    VARCHAR(4000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_comments_story ON comments (story_id);

CREATE TABLE likes (
    user_id    BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    story_id   BIGINT NOT NULL REFERENCES stories (id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, story_id)
);
CREATE INDEX idx_likes_story ON likes (story_id);
